modLoader="javafml"
loaderVersion="[43,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/LetSleepingDogsLie/issues"

[[mods]]
    modId="dogslie"
    version="${file.jarVersion}" #mandatory
    displayName="Let Sleeping Dogs Lie"
    displayURL="https://ichun.me/"
    authors="iChun"
    description='''
    Lets dogs lie.
    '''

[[dependencies.dogslie]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dogslie]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
