modLoader="javafml"
loaderVersion="[38,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/LetSleepingDogsLie/issues"

[[mods]]
    modId="dogslie"
    version="${file.jarVersion}" #mandatory
    displayName="Let Sleeping Dogs Lie"
    displayURL="https://ichun.me/"
    authors="iChun"
    description='''
    Lets dogs lie.
    '''

[[dependencies.dogslie]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dogslie]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
